aiakos/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as django_auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView, TemplateView

from . import views
from .openid_provider.views import ConfigurationView

urlpatterns = [
	url(r'^$', login_required(RedirectView.as_view(url=settings.HOME_URL)), name='home'),

	url(r'^apps/$', login_required(TemplateView.as_view(template_name='apps.html')), name='apps'),

	url(r'^admin/', admin.site.urls),

	url(r'^accounts/', include('django_extauth.urls', namespace='extauth')),
	url(r'^accounts/login/$', views.AuthView.as_view(), name='login'),
	url(r'^accounts/logout/$', django_auth_views.logout, name='logout'),
	url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
		django_auth_views.password_reset_confirm, name='password_reset_confirm'),
	url(r'^accounts/reset/done/$', django_auth_views.password_reset_complete, name='password_reset_complete'),
	url(r'^accounts/password-change/$', login_required(views.password_change), name="custom-password-change"),

	url(r'^oauth/', include('aiakos.openid_provider.urls', namespace='openid_provider')),

	url(r'^\.well-known/openid-configuration$', ConfigurationView.as_view()),
	url(r'^', include('django_profile_oidc.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aiakos/openid_provider/models/userconsent.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _

from .client import Client


class UserConsent(models.Model):
	class Meta:
		verbose_name = _("user consent")
		verbose_name_plural = _("user consents")
		unique_together = ('user', 'client')

	user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("user"))
	client = models.ForeignKey(Client, verbose_name=_("client"))
	_scope = models.TextField(default='', verbose_name=_("scopes"))

	date_given = models.DateTimeField(verbose_name=_("date given"), auto_now_add=True)
	date_updated = models.DateTimeField(verbose_name=_("date updated"), auto_now=True)

	@property
	def scope(self):
		return set(self._scope.split())

	@scope.setter
	def scope(self, value):
		self._scope = ' '.join(value)

	def __str__(self):
		return '{0} - {1}'.format(self.client, self.user)

aiakos/templates/apps.html
{% extends 'base.html' %}
{% load i18n staticfiles %}

{% block content %}

<div class="row">
	<div class="col-md-12">
		<h2>{% trans 'Your apps' %}</h2>
		<div class="row">
			{% for consent in request.user.userconsent_set.all %}
				<div class="col-sm-6 col-md-4">
					<a href="{{consent.client.profile.website}}" class="thumbnail">
						<img src="{{consent.client.profile.picture}}" style="height: 200px; width: 100%; display: block;">
						<span class="caption" style="font-size: 2em; text-align: center; width: 100%; display: block; text-decoration: none !important;">
							{{consent.client.profile.name}}
						</span>
					</a>
				</div>
			{% endfor %}
		</div>
	</div>
</div>

{% endblock %}

aiakos/templates/base.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<title>{{request.get_host|capfirst}} - Aiakos</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="{{bootstrap_theme.url}}" integrity="{{bootstrap_theme.integrity}}" crossorigin="anonymous">

	<style>
	body { padding-top: 70px; }
	.navbar-brand { line-height: 50px; padding: 0 15px; }
	.navbar-brand img { display: inline; height: 24px; padding-right: 10px; }
	</style>
  </head>
  <body>

	<nav class="navbar navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="/">
					{{request.get_host|capfirst}} - Aiakos
				</a>
			</div>

			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class="{% if request.resolver_match.url_name == 'apps' %}active{% endif %}"><a href="{% url 'apps' %}">Apps</a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					{% if user.is_staff %}
					<li>
						<a href="/admin/">Admin</a>
					</li>
					{% endif %}
					{% if user.is_authenticated %}
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
							{% if user.profile.picture %}
							<img src="{{user.profile.picture}}" style="height: 20px;">
							{% else %}
							{{user}}
							{% endif %}
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu" style="width: 250px;">
							<li><a style="white-space: normal;">
								{% blocktrans trimmed %}
									Signed in as <strong>{{user}}</strong>
								{% endblocktrans %}
							</a></li>
							<li role="separator" class="divider"></li>
							<li><a href="{{user.get_absolute_url}}">Your profile</a></li>
							<li class="{% if request.resolver_match.url_name == 'identities' %}active{% endif %}"><a href="{% url 'extauth:identities' %}">External identites</a></li>
							<li role="separator" class="divider"></li>
							<li><a href="{% url 'custom-password-change' %}">Password change</a></li>
							<li role="separator" class="divider"></li>
							<li><a href="{% url 'logout' %}">Sign out</a></li>
						</ul>
					</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>
	<div class="container">
		{% for message in messages %}
			<div class="alert alert-info {{ message.tags }}" role="alert">{{ message }}</div>
		{% endfor %}

		{% block content %}
		{% endblock %}
	</div>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

	<script>
	$(document).ready(function(){
		$(".datetime").each(function(){
			$(this).text((new Date($(this).text())).toLocaleString())
		})
	})
	</script>
  </body>
</html>